create table if not exists users (
    id bigint primary key generated by default as identity,
    username text not null unique,
    email text not null,
    password text not null,
    role text not null,
    created_at timestamp default now()
);
