create table if not exists trainings (
    id bigint primary key generated by default as identity,
    date date not null default current_date,
    notes text
);

create table if not exists exercises (
    id bigint primary key generated by default as identity,
    training_id bigint not null references trainings on delete cascade,
    name text not null,
    repeats int not null,
    weight numeric not null,
    time_sec int
);
